const pairSeeds = [
  ['geo', 'geo-intent-mining', 'GEO 项目怎样找到真正影响采购决策的高价值提问？', '从认知、需求、对比到决策，识别客户会向 AI 提出的真实问题，而不是继续沿用传统关键词词库。', ['GEO', '用户意图', '采购决策'], 620, '征集中', 'b2b-geo-intent-map', 'B2B GEO 用户意图地图构建法', '把搜索词、销售对话和 AI 提问整理成覆盖采购全周期的分层意图库。', ['GEO', '意图地图', '销售洞察']],
  ['geo', 'brand-fact-library', '企业产品资料怎样变成大模型可理解、可核验的品牌事实库？', '统一产品参数、资质、案例、服务边界和版本口径，并为每项事实保留可核验的来源证据。', ['GEO', '品牌事实库', '知识图谱'], 760, '已完成', 'geo-brand-knowledge-graph', 'GEO 品牌事实库与知识图谱搭建指南', '定义品牌实体、关系、证据、版本和责任人，让产品信息可被 AI 准确理解与交叉验证。', ['知识图谱', '品牌资产', '可信内容']],
  ['geo', 'ai-citable-content', '产品内容怎样写，才更容易被大模型准确引用而不是误读？', '探索兼顾用户阅读、AI 理解、事实准确和来源可追溯的结构化内容表达方式。', ['GEO', '内容结构', 'AI 引用'], 540, '萃取中', 'ai-citable-writing', 'AI 可引用内容的结构化写作规范', '通过实体清晰、问答组织、证据标注和版本管理，提高内容被大模型正确引用的概率。', ['内容生产', '结构化写作', 'GEO']],
  ['geo', 'trusted-geo-sources', 'GEO 内容应发布到哪些信源，如何避免低质海投和 AI 投毒？', '建立可信媒体、行业平台和品牌自有渠道的选择标准，拒绝虚假内容和短期投机。', ['GEO', '可信信源', '内容分发'], 720, '征集中', 'trusted-geo-distribution', '可信 GEO 信源选择与发布策略', '根据权威性、相关性、可追溯性和收录表现选择渠道，形成长期可信的信源组合。', ['可信 GEO', '信源策略', '内容分发']],
  ['geo', 'geo-compliance-review', '医疗、金融等行业做 GEO，怎样避免内容与宣传合规风险？', '识别夸大承诺、资质误用、数据失真和越界建议，并建立强制人工复核机制。', ['GEO', '内容合规', '风险治理'], 880, '部分完成', 'high-risk-geo-compliance', '高风险行业 GEO 合规审校手册', '提供风险分级、禁止表达、证据留存和人工复核清单，适用于医疗、金融等敏感行业。', ['合规审校', '高风险行业', 'GEO']],
  ['geo', 'geo-competitor-gap', '竞品已占据 AI 推荐位时，怎样找到可以突破的认知空档？', '分析竞品被推荐的原因、引用信源和未满足问题，找到品牌可以建立优势认知的位置。', ['GEO', '竞品分析', '品牌认知'], 650, '已完成', 'geo-competitor-gap-analysis', 'GEO 竞品认知差距分析方法', '从用户提问、AI 答案、引用信源和品牌事实四个层面识别可突破的认知空档。', ['竞品分析', '认知差距', 'GEO']],
  ['geo', 'geo-effect-attribution', 'GEO 上线后，怎样判断效果来自真实优化而不是模型波动？', '通过基线、对照和重复测试，区分真实效果、平台更新和模型回答的随机变化。', ['GEO', '效果归因', '实验设计'], 790, '征集中', 'geo-measurement-experiment', 'GEO 效果监测与归因实验指南', '用稳定样本、对照组和变更日志区分真实优化、平台更新与随机波动。', ['效果监测', '归因实验', 'GEO']],
  ['geo', 'geo-lead-attribution', '如何把 GEO 带来的 AI 咨询线索接入销售并追踪成交？', '打通 AI 咨询、页面访问、留资、商机、报价和成交，避免 GEO 只看曝光不看收入。', ['GEO', '销售线索', '转化归因'], 740, '萃取中', 'geo-revenue-attribution', 'GEO 线索到成交的全链路归因方法', '统一来源标记、CRM 字段和转化漏斗，把 AI 可见度连接到有效商机与实际收入。', ['转化漏斗', 'CRM', 'GEO']],
  ['geo', 'geo-partner-delivery', '全国服务商交付 GEO 项目，怎样保证诊断和复盘口径一致？', '解决不同服务商在资料收集、内容生产、验收和复盘上的质量与标准差异。', ['GEO', '服务商管理', '标准交付'], 920, '已完成', 'geo-partner-delivery-sop', 'GEO 服务商标准化交付 SOP', '覆盖售前诊断、资料收集、执行、验收和续费复盘，保证跨区域团队使用同一交付标准。', ['交付 SOP', '渠道管理', 'GEO']],
  ['marketing', 'ai-campaign-content-pack', '市场团队怎样用 AI 把一份产品资料变成完整 Campaign 内容包？', '一次生成文章、海报文案、销售物料、邮件和短视频脚本，同时保持品牌口径一致。', ['AI 营销', '内容生产', 'Campaign'], 520, '征集中', 'ai-marketing-content-pipeline', '企业 AI 营销内容流水线搭建指南', '规定素材输入、内容生成、品牌校准和多渠道适配流程，让一份产品资料支持完整 Campaign。', ['AI 营销', '内容流水线', '品牌一致性']],
  ['marketing', 'ai-ad-creative-review', '广告创意批量生成后，怎样筛掉同质化和不可投放内容？', '建立创意质量、品牌一致性和广告合规的统一判断标准，减少人工逐条返工。', ['AI 广告', '创意评审', '投放合规'], 580, '未完成', 'ai-ad-creative-evaluation', 'AI 广告创意评审与淘汰规则', '用差异度、信息准确性、品牌匹配和平台合规四类指标筛选可投放创意。', ['广告创意', '质量评估', 'AI 营销']],
  ['marketing', 'search-geo-intent-fusion', '搜索广告词和 AI 对话问题怎样形成统一的用户意图资产？', '打通传统搜索需求与生成式搜索中的场景化提问，避免维护两套互不相通的词库。', ['搜索广告', 'GEO', '意图资产'], 610, '征集中', 'search-geo-intent-method', '搜索广告与 GEO 意图融合方法', '建立统一意图分类、内容映射和投放复盘机制，让搜索与 AI 营销共享同一需求资产。', ['搜索营销', '意图融合', 'GEO']],
  ['marketing', 'conversational-brand-ad', 'AI 对话式品牌广告怎样设计问答路径并推动用户留资？', '在回答产品问题的同时完成需求判断、异议处理和转化引导，又不让用户感到被强行推销。', ['对话广告', '用户转化', 'AI 品牌营销'], 670, '萃取中', 'conversational-ad-conversion', '对话式品牌广告转化路径设计手册', '覆盖开场、追问、产品解释、异议处理和留资节点，兼顾用户体验与商业转化。', ['对话设计', '品牌广告', '转化路径']],
  ['marketing', 'vibe-landing-page', '广告落地页如何用 Vibe Coding 快速上线并完成 A/B 测试？', '让市场人员自主制作页面，同时保障组件复用、数据埋点、发布安全和失败回滚。', ['Vibe Coding', '落地页', 'A/B 测试'], 560, '征集中', 'vibe-landing-page-workflow', '市场人员 Vibe Coding 落地页工作流', '包含需求模板、组件规范、埋点检查、A/B 实验、上线审批和一键回滚方法。', ['Vibe Coding', '增长实验', '落地页']],
  ['sales', 'vibe-sales-crm', '销售团队如何用 Vibe Coding 搭建轻量商机管理系统？', '管理客户、联系人、商机阶段、跟进记录和预计回款，同时保持字段简单、团队愿意使用。', ['Vibe Coding', '销售管理', 'CRM'], 780, '征集中', 'lightweight-sales-system', '轻量销售管理系统搭建手册', '定义最小数据结构、权限、商机状态和异常检查，让业务团队可以快速搭建并持续迭代。', ['销售系统', 'Vibe Coding', 'CRM']],
  ['sales', 'sales-quote-approval-vibe', '销售团队如何用 Vibe Coding 搭建可追踪的报价与折扣审批台？', '将报价版本、折扣阈值、审批链路和例外处理统一起来，让销售更快响应客户，同时保留完整过程记录。', ['Vibe Coding', '报价审批', '销售运营'], 720, '已完成', 'sales-quote-approval-playbook', '销售报价与折扣审批台搭建手册', '以最小字段、审批规则、异常升级和审计日志为核心，搭建可供销售团队持续迭代的轻量审批工具。', ['销售系统', '审批流程', 'Vibe Coding']],
  ['sales', 'lead-routing-rules', '线索量增加后，怎样自动分配并处理撞单和超时未跟进？', '建立公平、可解释且能处理地域、行业、客户归属和销售请假等例外情况的规则。', ['线索分配', '销售运营', '自动化'], 590, '已完成', 'lead-routing-conflict-rules', '销售线索分配与冲突处理规则库', '覆盖地域、行业、客户归属、超时回收、撞单仲裁和重新分配等关键场景。', ['销售运营', '线索治理', '规则库']],
  ['sales', 'ai-poc-qualification', '企业 AI 产品销售怎样在首轮访谈中判断客户是否值得进入 POC？', '快速判断场景价值、数据条件、客户决策链、预算意愿和潜在交付风险。', ['企业 AI', 'POC', '销售访谈'], 690, '征集中', 'ai-poc-qualification-scorecard', '企业 AI 项目 POC 资格评估方法', '通过结构化访谈和评分卡判断项目是否具备价值、数据、角色和商业条件。', ['POC 评估', '企业销售', '评分卡']],
  ['sales', 'ai-presales-proposal', '售前怎样基于知识库快速生成客户版方案，又避免参数和案例编造？', '方案需要引用正确的产品能力、客户案例和实施边界，并保留可供售前复核的事实依据。', ['AI 售前', '方案生成', '事实校验'], 830, '已完成', 'ai-presales-proposal-workflow', '企业 AI 售前方案生成与事实校验流程', '规定知识检索、内容生成、证据引用、参数核对和人工审批节点，降低方案幻觉风险。', ['售前方案', '知识库', '事实校验']],
  ['geo', 'geo-visibility-baseline', '如何测清企业 AI 产品在主流大模型中的真实可见度？', '建立固定问题集，持续监测品牌提及、推荐位置、引用来源和回答倾向，避免每次测试口径都不同。', ['GEO', '品牌诊断', 'AI 搜索'], 680, '征集中', 'b2b-geo-visibility', 'B2B 品牌 GEO 可见度诊断与评分手册', '用固定问题集、跨平台抽样和四维评分，建立可复测的品牌 AI 可见度基线。', ['GEO', '诊断评分', 'B2B 营销']],
  ['sales', 'ai-sales-call-review', '销售通话如何由 AI 自动生成纪要、异议分类和下一步行动？', '减少手工记录，同时确保客户角色、需求、异议、承诺和下一步负责人不会遗漏。', ['销售会话', 'AI 纪要', '跟进管理'], 510, '征集中', 'ai-sales-followup-workflow', 'AI 销售会话复盘与跟进工作流', '从通话中提取角色、需求、异议、承诺和行动项，并自动同步到商机记录。', ['销售复盘', 'AI 助手', '行动项']],
  ['sales', 'quote-discount-approval', '报价与折扣审批工具怎样兼顾销售效率、毛利和过程留痕？', '缩短审批时间，同时控制特殊折扣、避免报价版本混乱并保留完整审计记录。', ['报价管理', '审批流程', '销售工具'], 640, '征集中', 'quote-approval-system', '企业软件报价与折扣审批系统设计指南', '包含价格规则、审批阈值、特殊情况、版本控制和审计日志的产品设计方法。', ['报价审批', '毛利管理', '销售系统']],
  ['sales', 'partner-lifecycle-system', '渠道与服务商管理系统怎样看清报备、交付、回款与续费？', '统一管理合作伙伴从线索报备、项目交付到回款和续约的完整状态。', ['渠道管理', '服务商', '销售系统'], 860, '部分完成', 'ai-channel-lifecycle', 'AI 产品渠道全生命周期管理方法', '覆盖伙伴准入、线索报备、冲突处理、交付评价、结算和续约的完整管理机制。', ['渠道运营', '伙伴管理', '全生命周期']],
  ['knowledge', 'knowledge-ingestion-governance', '上万份企业文档进入 AI 知识库前，怎样清洗、分级和处理权限？', '解决重复、过期、冲突、敏感和无负责人的文档，避免知识库从上线开始就失控。', ['AI 知识库', '内容治理', '权限管理'], 900, '已完成', 'enterprise-knowledge-governance', '企业知识库内容治理与准入规范', '规定文档清洗、分类、权限、责任人、有效期、冲突处理和下线流程。', ['知识治理', '权限管理', '企业知识库']],
  ['knowledge', 'rag-quality-diagnosis', '知识库问答效果不好时，如何定位是文档、切片、检索还是生成问题？', '建立可重复的分阶段诊断和效果评测流程，不再依赖团队凭感觉调参数。', ['RAG', '问答评测', '问题诊断'], 840, '征集中', 'rag-evaluation-diagnostics', 'RAG 问答效果诊断与评测手册', '通过标准问题集和检索、排序、生成分段指标，快速定位回答质量问题。', ['RAG 评测', '知识库', '质量诊断']],
  ['knowledge', 'ai-service-handoff', 'AI 客服何时应继续回答、追问、转人工或直接拒答？', '处理信息不足、用户情绪、敏感问题和高风险业务，形成可执行的人机协作边界。', ['AI 客服', '转人工', '对话决策'], 730, '征集中', 'ai-service-decision-rules', 'AI 客服对话决策与人工接管规则', '定义意图置信度、追问策略、情绪识别、转人工阈值和拒答边界。', ['AI 客服', '人机协作', '决策规则']],
  ['knowledge', 'service-knowledge-lifecycle', '多产品线客服知识怎样持续更新，避免新旧口径同时出现？', '打通产品变更、知识发布、客服培训和旧答案下线，保证所有渠道使用同一版本。', ['客服知识库', '版本管理', '内容运营'], 660, '已完成', 'service-knowledge-lifecycle-guide', '客服知识全生命周期管理机制', '覆盖知识创建、审核、生效、培训、版本更新、失效回收和使用反馈。', ['知识运营', '客服管理', '版本治理']],
  ['knowledge', 'ai-service-quality-loop', '如何用 AI 质检客服会话，并推动知识库持续补洞？', '从真实对话中识别错误回答、服务风险和知识缺口，形成可以追踪的改进闭环。', ['AI 质检', '客服运营', '知识补洞'], 710, '萃取中', 'service-quality-knowledge-loop', '客服质检到知识库迭代的闭环工作流', '把问题发现、原因归类、知识修订、上线验证和效果复测连接成完整闭环。', ['客服质检', '知识迭代', '运营闭环']],
  ['operations', 'ai-customer-activation', '企业客户购买 AI 产品后用不起来，怎样设计前 30 天激活？', '围绕首个业务场景、数据准备、管理员培训和价值验证完成有节奏的客户陪跑。', ['AI 产品', '客户激活', '交付运营'], 770, '征集中', 'ai-first-30-days', '企业 AI 产品前 30 天激活手册', '定义上线里程碑、角色分工、使用任务、价值验证和客户风险预警。', ['客户激活', 'AI 交付', '30 天计划']],
  ['operations', 'agent-operations-metrics', 'AI 智能体上线后，运营团队每天应该看哪些指标和失败样本？', '同时观察使用、效果、成本、风险和人工接管，而不是只关注调用次数。', ['AI 智能体', '运营指标', '失败分析'], 820, '已完成', 'agent-operations-metrics-guide', '企业 AI 智能体日常运营指标体系', '包含核心看板、失败样本分类、成本监控、风险预警和周期复盘机制。', ['智能体运营', '指标体系', '失败样本']],
  ['operations', 'ai-voice-of-customer', '客户反馈、销售异议和客服问题怎样汇成产品迭代优先级？', '统一收集销售、交付、客服和客户成功的信息，让产品团队基于证据排需求。', ['AI 产品运营', '客户声音', '需求优先级'], 630, '征集中', 'ai-product-voc-loop', '企业 AI 产品客户声音闭环方法', '统一收集、聚类、验证、排序和结果反馈，让业务问题持续进入产品迭代。', ['客户声音', '产品迭代', '运营闭环']],
];

const trackMeta = {
  geo: {
    context: '团队已有零散测试和内容尝试，但缺少跨平台、可复测、可归因的统一方法。',
    outline: ['怎样定义业务目标、测试范围和初始基线？', '哪些用户提问、品牌事实和信源必须纳入？', '执行过程中如何记录版本变化并处理异常？', '最终用哪些指标判断 GEO 产生了真实价值？'],
    result: 'GEO 不能从批量发文开始，而应先固定用户问题、品牌事实、可信信源和测量基线，再通过持续复测判断认知是否发生变化。',
    confidence: '品牌策略、内容运营、搜索营销和数据分析角色的独立实践相互印证。',
    gap: '跨平台引用变化的长期稳定性仍缺少更长周期的数据。',
  },
  marketing: {
    context: '市场团队已使用生成式工具，但内容输入、品牌校准、合规审核和效果复盘仍彼此割裂。',
    outline: ['这项营销动作服务哪个人群和业务目标？', '输入素材和品牌事实需要达到什么标准？', '哪些环节可以自动化，哪些必须人工确认？', '如何通过投放或实验数据持续改进？'],
    result: '有效的 AI 营销工作流必须先锁定目标受众和品牌事实，再批量生成、分层审核并用真实投放数据淘汰低价值内容。',
    confidence: '品牌、创意、媒介和增长团队提供了多轮项目经验。',
    gap: '不同广告平台对生成式内容的审核规则仍需要持续更新。',
  },
  sales: {
    context: '当前流程依赖表格、群消息和个人经验，信息重复录入、状态不透明，异常通常发现得太晚。',
    outline: ['真正需要被管理的对象、字段和状态有哪些？', '角色权限和关键流转规则如何定义？', '自动化在哪些节点触发，异常如何回退？', '怎样让销售愿意使用并保持数据质量？'],
    result: '销售工具不应从功能列表开始，而应先统一商机对象、状态流转和责任边界，只自动化高频且规则稳定的动作。',
    confidence: '销售一线、销售运营、售前和渠道管理角色提供了相互补充的案例。',
    gap: '复杂集团客户的跨区域归属与联合跟进仍需补充规则。',
  },
  knowledge: {
    context: '企业已有大量文档和客服对话，但知识来源、权限、版本和质量责任不清，容易产生错误回答。',
    outline: ['知识范围、来源和责任人如何确定？', '内容如何清洗、切分、授权和持续更新？', '问答失败时怎样定位到具体环节？', '如何通过真实使用反馈推动知识迭代？'],
    result: '知识库效果首先取决于内容治理和责任机制，其次才是模型与检索参数；高风险问题必须明确转人工和拒答边界。',
    confidence: '知识工程、客服运营、产品和合规角色的实践形成较高一致性。',
    gap: '复杂权限继承和跨系统知识同步的案例仍不充分。',
  },
  operations: {
    context: '产品已具备 AI 能力，但客户激活、日常运营、失败分析和需求回流还没有形成稳定闭环。',
    outline: ['客户首先需要完成哪个可验证的业务结果？', '上线与运营阶段各角色承担什么责任？', '哪些使用、质量、成本和风险指标必须持续观察？', '失败样本和客户声音怎样进入产品迭代？'],
    result: '企业 AI 产品运营的重点不是提高调用量，而是让客户持续完成可验证的业务任务，并把失败样本转化为产品、知识和流程改进。',
    confidence: '产品运营、客户交付和智能体研发团队提供了真实上线经验。',
    gap: '跨行业客户的价值指标仍需要按场景继续细分。',
  },
};

const owners = ['周宁', '梁知远', '陈默', '顾言', '林澈', '许望', '唐简', '沈知行'];
const currentUserPublishedTaskIds = new Set([
  'geo-visibility-baseline',
  'vibe-sales-crm',
  'sales-quote-approval-vibe',
]);

export const tasks = pairSeeds.map((seed, index) => {
  const [track, id, title, brief, tags, reward, status, knowHowId] = seed;
  const meta = trackMeta[track];
  const completed = ['已完成', '部分完成'].includes(status);
  return {
    id,
    title,
    brief,
    description: `${brief} ${meta.context} 希望获得来自真实项目的判断逻辑、执行步骤、检查标准和失败案例。`,
    tags,
    reward,
    status,
    track,
    deadline: status === '征集中' ? `07 月 ${19 + (index % 10)} 日 18:00` : status === '萃取中' ? '已于 07 月 16 日截止' : '已结束',
    deadlineShort: status === '征集中' ? `剩 ${2 + (index % 8)} 天` : status === '萃取中' ? '正在萃取' : status,
    participants: status === '未完成' ? 0 : status === '征集中' ? 2 + (index % 9) : 6 + (index % 8),
    updated: id === 'geo-visibility-baseline' ? '4 天前' : index < 4 ? `${12 + index * 17} 分钟前` : `${1 + (index % 6)} 天前`,
    owner: owners[index % owners.length],
    avatar: owners[index % owners.length][0],
    isPublishedByCurrentUser: currentUserPublishedTaskIds.has(id),
    outline: meta.outline,
    result: meta.result,
    confidenceNote: meta.confidence,
    gapNote: meta.gap,
    resultAdopted: completed ? 5 + (index % 4) : undefined,
    resultTotal: completed ? 8 + (index % 5) : undefined,
    knowHowId: completed ? knowHowId : undefined,
  };
});

const taskGeneratedKnowHows = pairSeeds.map((seed, index) => {
  const [track, , , , , , , id, title, summary, tags] = seed;
  const sourceTask = tasks[index];
  return {
    id,
    title,
    summary,
    tags,
    track,
    version: `v${1 + (index % 3)}.${index % 4}`,
    contributors: 4 + (index % 10),
    updated: index < 5 ? `${index + 1} 天前` : `${1 + (index % 4)} 周前`,
    status: index % 7 === 5 ? '部分完成' : '完整',
    confidence: index % 7 === 5 ? '存在 1 项信息缺口' : index % 3 === 0 ? '高可信度' : '中高可信度',
    sourceTask: ['已完成', '部分完成'].includes(sourceTask.status) ? sourceTask.id : undefined,
    following: index < 2,
  };
});

const independentlyCreatedKnowHows = [
  {
    id: 'enterprise-agent-permission-governance',
    title: '企业 AI Agent 权限与高风险操作审批指南',
    summary: '按数据敏感度、操作影响和可逆性划分 Agent 权限，明确自动执行、执行前确认、人工审批和禁止操作的边界。',
    tags: ['AI Agent', '权限治理', '风险控制'],
    track: 'knowledge',
    version: 'v1.2',
    contributors: 11,
    updated: '1 天前',
    status: '完整',
    confidence: '高可信度',
    sourceTask: undefined,
    following: false,
  },
  {
    id: 'ai-poc-value-validation-30d',
    title: '企业 AI 项目 30 天 POC 价值验证方法',
    summary: '从业务基线、样本准备、角色分工到结果复测，帮助团队在有限周期内判断 AI 项目是否值得继续投入。',
    tags: ['AI POC', '价值验证', '项目决策'],
    track: 'operations',
    version: 'v2.0',
    contributors: 9,
    updated: '2 天前',
    status: '完整',
    confidence: '中高可信度',
    sourceTask: undefined,
    following: false,
  },
  {
    id: 'b2b-discovery-evidence-map',
    title: '复杂 B2B 销售需求访谈与证据地图方法',
    summary: '把客户表述拆分为业务目标、现状证据、决策角色、约束和成功标准，减少售前方案建立在模糊需求之上。',
    tags: ['B2B 销售', '需求访谈', '证据地图'],
    track: 'sales',
    version: 'v1.3',
    contributors: 8,
    updated: '3 天前',
    status: '完整',
    confidence: '高可信度',
    sourceTask: undefined,
    following: false,
  },
  {
    id: 'brand-fact-consistency-audit',
    title: '多渠道品牌事实一致性巡检机制',
    summary: '定期核对官网、销售物料、媒体内容和 AI 知识库中的产品事实，定位冲突口径并推动责任人完成统一修订。',
    tags: ['品牌事实', '内容治理', '一致性巡检'],
    track: 'marketing',
    version: 'v1.1',
    contributors: 7,
    updated: '4 天前',
    status: '部分完成',
    confidence: '存在 1 项信息缺口',
    sourceTask: undefined,
    following: false,
  },
  {
    id: 'geo-source-quality-audit',
    title: 'GEO 引用信源质量审计与风险排查手册',
    summary: '从权威性、相关性、证据完整度和异常传播四个维度审查 AI 引用信源，识别低质内容、错误事实和潜在投毒风险。',
    tags: ['GEO', '信源审计', '内容风险'],
    track: 'geo',
    version: 'v2.2',
    contributors: 12,
    updated: '1 周前',
    status: '完整',
    confidence: '中高可信度',
    sourceTask: undefined,
    following: false,
  },
  {
    id: 'human-review-exception-handoff',
    title: '人机协作工作流的人工复核与异常接管规范',
    summary: '根据置信度、业务风险和信息完整性设置人工接管条件，并为退回、修正、重试和责任追踪提供统一操作规则。',
    tags: ['人机协作', '人工复核', '异常接管'],
    track: 'knowledge',
    version: 'v1.0',
    contributors: 10,
    updated: '2 周前',
    status: '完整',
    confidence: '中高可信度',
    sourceTask: undefined,
    following: false,
  },
];

export const knowHows = [...taskGeneratedKnowHows, ...independentlyCreatedKnowHows];

export const notifications = [
  {
    id: 1,
    messageType: 'knowhow',
    type: 'result',
    category: '贡献采纳',
    title: '你的贡献被采纳了',
    pointsChange: 168,
    detail: '“GEO 品牌事实库与知识图谱搭建指南”采纳了你提交的版本治理与证据追溯方法。168 积分已经到账，本次采纳也会计入你的 GEO 领域声誉。',
    time: '18 分钟前',
    timestamp: '2026 年 7 月 19 日 14:42',
    unread: true,
    body: [
      '萃取 Agent 已完成本轮内容整合。你提出的“每项品牌事实绑定责任人、生效时间和证据版本”被判定为影响最终结果的关键实践，已进入当前正式版本。',
      '本次采纳比例为 21%，对应 168 积分。后续该 Know-how 产生使用权收入或 AI Skill 有效调用时，你还会按照当前版本的贡献比例持续获得分成。',
    ],
    facts: [['关联 Know-how', 'GEO 品牌事实库与知识图谱搭建指南'], ['采纳内容', '版本治理与证据追溯'], ['本次收益', '168 积分'], ['贡献状态', '已进入正式版本']],
    actionLabel: '查看 Know-how',
    actionTo: '/know-how/geo-brand-knowledge-graph',
  },
  {
    id: 2,
    messageType: 'task',
    type: 'task',
    category: '任务进展',
    title: '你发布的任务收到新贡献',
    detail: '“如何测清企业 AI 产品在主流大模型中的真实可见度？”新增了 2 份密封贡献，目前已有 6 位实践者参与。距离截止还有 4 天，你暂时无需进行操作。',
    time: '1 小时前',
    timestamp: '2026 年 7 月 19 日 14:00',
    unread: true,
    body: [
      '两位新的实践者分别补充了跨模型抽样方法和异常波动排查经验。征集期间贡献内容保持密封，任务发起人和其他贡献者均不能提前查看原文。',
      '任务将在 7 月 23 日 18:00 截止。截止后，萃取 Agent 会自动检查内容有效性、识别信息冲突，并生成首轮 Know-how 成果与积分分配结果。',
    ],
    facts: [['关联任务', '企业 AI 产品 GEO 可见度诊断'], ['当前参与', '6 位实践者'], ['新增贡献', '2 份'], ['距离截止', '4 天']],
    actionLabel: '查看任务进展',
    actionTo: '/task/geo-visibility-baseline',
  },
  {
    id: 3,
    messageType: 'task',
    type: 'match',
    category: '领域匹配',
    title: '有一项任务与你的领域匹配',
    detail: '销售团队正在征集使用 Vibe Coding 搭建轻量商机管理系统的真实方法。任务与你的“销售运营”和“企业 AI”领域高度匹配，当前悬赏为 780 积分。',
    time: '昨天',
    timestamp: '2026 年 7 月 18 日 16:25',
    unread: true,
    body: [
      '任务希望找到一套小团队也能落地的商机管理方法，重点覆盖客户、联系人、商机阶段、跟进记录、预计回款和异常提醒。',
      '系统根据你的领域标签、历史贡献和已发布 Know-how 判断匹配度为 89%。如果你参与，可以选择接受对话 Agent 访谈，或直接提交现有文档和实践记录。',
    ],
    facts: [['匹配领域', '销售运营 · 企业 AI'], ['匹配度', '89%'], ['悬赏积分', '780 积分'], ['任务状态', '征集中']],
    actionLabel: '查看匹配任务',
    actionTo: '/task/vibe-sales-crm',
  },
  {
    id: 4,
    messageType: 'knowhow',
    type: 'update',
    category: '版本更新',
    title: '关注的 Know-how 更新到 v2.1',
    detail: '“企业知识库内容治理与准入规范”发布了 v2.1，新版本增加敏感资料权限继承、离职人员权限回收和跨部门知识访问的处理规则。',
    time: '2 天前',
    timestamp: '2026 年 7 月 17 日 10:18',
    unread: false,
    body: [
      '本次更新来自 5 位知识治理和信息安全实践者的补充，重点解决企业知识库接入原有文档系统后，权限关系无法准确继承的问题。',
      '你当前关注的是最新版本，因此阅读页已经自动切换到 v2.1。如果该 Know-how 已通过 AI Skill 接入企业产品，则仍保持原版本，确认后才会升级。',
    ],
    facts: [['Know-how', '企业知识库内容治理与准入规范'], ['版本变化', 'v2.0 → v2.1'], ['新增贡献者', '5 位'], ['更新范围', '权限继承与回收']],
    actionLabel: '查看新版本',
    actionTo: '/know-how/enterprise-knowledge-governance',
  },
  {
    id: 5,
    messageType: 'task',
    type: 'task',
    category: '任务进展',
    title: '关注的任务已进入萃取阶段',
    detail: '“产品内容怎样写，才更容易被大模型准确引用而不是误读？”已经停止接收新贡献。萃取 Agent 正在整理 8 位实践者提交的内容和冲突观点。',
    time: '3 天前',
    timestamp: '2026 年 7 月 16 日 18:06',
    unread: false,
    body: [
      '任务已按计划截止，所有有效贡献现已解封并进入自动萃取。Agent 将先检查内容是否回应任务，再提取判断逻辑、执行步骤、失败条件和验证标准。',
      '预计本轮萃取需要 1 至 2 个工作日。完成后你会收到最终 Know-how、贡献采纳比例和积分结算通知。',
    ],
    facts: [['关联任务', 'AI 可引用内容结构'], ['有效贡献者', '8 位'], ['当前阶段', '萃取中'], ['预计完成', '1–2 个工作日']],
    actionLabel: '查看萃取进展',
    actionTo: '/task/ai-citable-content',
  },
  {
    id: 6,
    messageType: 'knowhow',
    type: 'update',
    category: '使用反馈',
    title: '你贡献的 Know-how 收到新的使用反馈',
    detail: '一位企业市场负责人对“B2B 品牌 GEO 可见度诊断与评分手册”提交了使用反馈，认为复测基线部分有效，并建议补充跨部门责任边界。',
    time: '4 天前',
    timestamp: '2026 年 7 月 15 日 11:36',
    unread: false,
    body: [
      '使用者在月度 GEO 复测中采用了固定问题集、模型版本记录和引用来源留档方法，认为这三项规则显著减少了团队对数据波动的争议。',
      '反馈同时指出，当品牌事实、公开页面和销售口径不一致时，当前版本尚未明确最终确认人。该建议已经进入下一轮迭代候选问题。',
    ],
    facts: [['关联 Know-how', 'B2B 品牌 GEO 可见度诊断与评分手册'], ['反馈类型', '真实使用反馈'], ['有效结论', '固定基线与证据留档'], ['待补充', '跨部门责任边界']],
    actionLabel: '查看反馈位置',
    actionTo: '/know-how/b2b-geo-visibility',
  },
  {
    id: 7,
    messageType: 'knowhow',
    type: 'update',
    category: '接口提醒',
    title: 'AI Skill 有可升级版本',
    detail: '你接入的“企业知识库内容治理与准入规范”AI Skill 已发布新版本。当前接口仍锁定 v2.0，升级前可以先查看 v2.1 的变化说明。',
    time: '5 天前',
    timestamp: '2026 年 7 月 14 日 09:12',
    unread: false,
    body: [
      '为避免企业 Agent 的输出逻辑在未确认时发生变化，平台没有自动升级当前接口。现有访问密钥和调用地址可以继续正常使用。',
      '确认升级后，后续有效执行将使用 v2.1；如新版本不符合现有业务流程，你可以继续保持 v2.0，直到完成内部验证。',
    ],
    facts: [['AI Skill', '企业知识库内容治理与准入规范'], ['当前版本', 'v2.0'], ['可升级版本', 'v2.1'], ['接口状态', '正常可用']],
    actionLabel: '查看版本并决定',
    actionTo: '/know-how/enterprise-knowledge-governance',
  },
  {
    id: 8,
    messageType: 'system',
    type: 'result',
    category: '收益结算',
    title: '本周 AI Skill 调用版税已结算',
    pointsChange: 94,
    detail: '你参与贡献的 3 个 Know-how 本周共产生 126 次有效执行，扣除平台执行成本后，你获得 94 积分调用版税，积分已经进入可提现收益。',
    time: '6 天前',
    timestamp: '2026 年 7 月 13 日 08:30',
    unread: false,
    body: [
      '本次结算仅统计成功完成业务任务的有效执行。失败、超时和平台自动重试没有计入客户调用额度，也没有进入贡献者分成。',
      '收益来自你在 GEO 诊断、企业知识库治理和售前方案生成三个 Know-how 中的版本贡献。详细分成比例会随各版本的采纳关系保留。',
    ],
    facts: [['结算周期', '7 月 6 日–7 月 12 日'], ['有效执行', '126 次'], ['参与 Know-how', '3 个'], ['本周版税', '94 积分']],
    actionLabel: '查看我的收益',
    actionTo: '/profile',
  },
  {
    id: 9,
    messageType: 'system',
    type: 'task',
    category: '积分提醒',
    title: '本月有一笔奖励积分即将到期',
    detail: '你在 2026 年 1 月获得的 120 奖励积分将在本月底到期。任务悬赏、Know-how 阅读和 AI Skill 调用均可优先使用这部分积分。',
    time: '7 天前',
    timestamp: '2026 年 7 月 12 日 09:20',
    unread: false,
    body: [
      '即将到期的积分来自新用户首次贡献奖励，不影响你通过任务采纳、Know-how 分成和 AI Skill 调用版税获得的长期有效积分。',
      '系统将在支付时自动优先抵扣最早到期的奖励积分。积分过期后不会影响领域声誉、历史贡献记录或已发布内容。',
    ],
    facts: [['积分类型', '平台奖励积分'], ['即将到期', '120 积分'], ['到期时间', '2026 年 7 月 31 日'], ['使用范围', '悬赏 · 阅读 · AI Skill']],
    actionLabel: '查看积分明细',
    actionTo: '/profile',
  },
  {
    id: 10,
    messageType: 'system',
    type: 'update',
    category: '平台更新',
    title: '消息中心与贡献记录展示方式已更新',
    detail: '消息现在通过系统、任务和 Know-how 三种类型直接标识。贡献记录也增加了关联版本信息，方便你快速确认内容被采用到哪个正式版本。',
    time: '8 天前',
    timestamp: '2026 年 7 月 11 日 17:45',
    unread: false,
    body: [
      '本次更新不会改变原有消息、关注关系或贡献数据。所有历史通知会按照系统、任务和 Know-how 三种类型展示，并继续保留关联内容的访问入口。',
      '贡献记录新增正式版本、采纳比例和收益状态三个字段。对于尚未完成萃取的任务，相关字段会在结果生成后自动补齐。',
    ],
    facts: [['消息类型', '系统 · 任务 · Know-how'], ['数据影响', '无数据迁移或删除'], ['历史消息', '全部保留'], ['生效状态', '已上线']],
    actionLabel: '查看个人中心',
    actionTo: '/profile',
  },
  {
    id: 11,
    messageType: 'task',
    type: 'task',
    category: '截止提醒',
    title: '你参与的任务将在明天停止接收贡献',
    detail: '“企业 RAG 知识库质量诊断与修复工作流”将在明天 18:00 截止。你的贡献草稿已经保存，但仍有两个诊断步骤尚未补充验证标准。',
    time: '9 天前',
    timestamp: '2026 年 7 月 10 日 10:05',
    unread: false,
    body: [
      '当前草稿已覆盖召回率排查、文档切片异常和答案引用核验，但“问题复现条件”和“修复后回归检查”仍缺少可以直接执行的判断标准。',
      '截止前你可以继续与对话 Agent 补充，也可以直接编辑草稿。任务截止后未正式提交的草稿不会进入萃取，也不会被其他参与者看到。',
    ],
    facts: [['关联任务', '企业 RAG 知识库质量诊断'], ['当前状态', '贡献草稿'], ['待补充', '2 项验证标准'], ['截止时间', '明天 18:00']],
    actionLabel: '继续补充贡献',
    actionTo: '/task/rag-quality-diagnosis',
  },
  {
    id: 12,
    messageType: 'system',
    type: 'match',
    category: '安全提醒',
    title: '你的账号完成了一次新的设备登录',
    detail: '账号于 7 月 9 日 09:28 在北京通过 Chrome 浏览器登录。若这是你的操作则无需处理；如有异常，建议立即检查账号与已生成的 AI Skill 密钥。',
    time: '10 天前',
    timestamp: '2026 年 7 月 9 日 09:28',
    unread: false,
    body: [
      '本次登录已经通过企业统一身份认证，设备信息与常用工作环境基本一致，因此平台没有中断会话。',
      '为了保护企业 Know-how 与接口调用权限，如发现异常登录，请尽快退出其他设备并重新生成可能泄露的 AI Skill 访问密钥。',
    ],
    facts: [['登录地点', '北京'], ['登录方式', '企业统一身份认证'], ['浏览器', 'Chrome'], ['风险判断', '低风险']],
    actionLabel: '检查账号信息',
    actionTo: '/profile',
  },
];

export const currentUser = {
  name: '钟源',
  handle: '@zhongyuan',
  initials: '钟',
  bio: '关注企业 AI 商业化、GEO 与销售运营，喜欢把一线经验沉淀成团队可以直接调用的工作流。',
  points: 1320,
  tags: ['GEO', '企业 AI', '销售运营'],
};
